#!/bin/bash

CONTIKI_PATH=/home/mountainsensing/contiki
ROUTER_PATH=/mountainsensing/rpl-border-router
PREFIX="2a01:348:24b:2::1/56"

RECIEVER_PATH=/home/mountainsensing/linux-gateway/src

RECIEVER_LOG_FILE=/ms/python/data/reciever-log

cd ${CONTIKI_PATH}/${ROUTER_PATH}
make z1-reset connect-router PREFIX=${PREFIX}

