#!/bin/bash

SCRIPT_PATH=/home/mountainsensing/linux-gateway/scripts

RECIEVER_PATH=/home/mountainsensing/linux-gateway/src

RECIEVER_LOG_FILE=/ms/python/data/reciever-log

cd $SCRIPT_PATH
screen -d -m -S router ./router-maintainer
sleep 20
cd ${RECIEVER_PATH}
screen -d -m -S gateway ./gateway.py -vf ${RECIEVER_LOG_FILE}  

